# Generated by Django 5.0.1 on 2024-02-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание предмета')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.inventory', verbose_name='Инвентарь')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Элемент инвентаря',
                'verbose_name_plural': 'Элементы инвентаря',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(related_name='inventories', through='trade.InventoryItem', to='trade.item', verbose_name='Предметы в инвентаре'),
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок предложения')),
                ('description', models.TextField(verbose_name='Описание предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('items_offered', models.ManyToManyField(related_name='trade_offers_offered', to='trade.item', verbose_name='Предлагаемые предметы')),
                ('items_requested', models.ManyToManyField(related_name='trade_offers_requested', to='trade.item', verbose_name='Желаемые предметы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложение обмена',
                'verbose_name_plural': 'Предложения обмена',
            },
        ),
    ]
