# Generated by Django 5.0.1 on 2024-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeoffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='title',
        ),
    ]
