# Generated by Django 5.0.1 on 2024-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='items_offered_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='items_requested_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
