# Generated by Django 5.0.1 on 2024-02-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_item_user_tradeoffer_items_offered_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
