# Generated by Django 5.0.1 on 2024-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название предмета'),
        ),
    ]
